################################################

POST http://127.0.0.1:5000/category/create
Content-Type: application/json

{
    "categoryName": "cartoon",
    "description": "tom & jerry"

}


#### get all products

Get http://127.0.0.1:5000/category/getall

################################################
#### get product by id

Get http://127.0.0.1:5000/category/getbyid/2

################################################
#### delete product by id

DELETE  http://127.0.0.1:5000/category/deletebyid/11

################################################
#### update by id

PUT  http://127.0.0.1:5000/category/updatebyid/3

Content-Type: application/json

{
    "categoryName": "new In Hell",
    "description": "At home"
}